version: "3.8"

services:

  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/channelqa

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: channelqa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: